# Generated by Django 3.2.3 on 2021-06-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
